//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.ValidatorMessages", typeof(ValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt text is required.
        /// </summary>
        internal static string AltTextIsRequired {
            get {
                return ResourceManager.GetString("AltTextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseFormat is required.
        /// </summary>
        internal static string BaseFormatIsRequired {
            get {
                return ResourceManager.GetString("BaseFormatIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseFormat must be at most {0} characters.
        /// </summary>
        internal static string BaseFormatMaxLength {
            get {
                return ResourceManager.GetString("BaseFormatMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be at most {0} characters.
        /// </summary>
        internal static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email content is required.
        /// </summary>
        internal static string EmailContentIsRequired {
            get {
                return ResourceManager.GetString("EmailContentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email content must not exceed {0} characters.
        /// </summary>
        internal static string EmailContentMaxLength {
            get {
                return ResourceManager.GetString("EmailContentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be at most {0} characters.
        /// </summary>
        internal static string EmailFromMaxLength {
            get {
                return ResourceManager.GetString("EmailFromMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender email is required.
        /// </summary>
        internal static string EmailSenderIsRequired {
            get {
                return ResourceManager.GetString("EmailSenderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension should look like &apos;jpg&apos;.
        /// </summary>
        internal static string ExtensionFormat {
            get {
                return ResourceManager.GetString("ExtensionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension is required.
        /// </summary>
        internal static string ExtensionIsRequired {
            get {
                return ResourceManager.GetString("ExtensionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be greater than 0.
        /// </summary>
        internal static string IdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("IdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt text must be at most {0} characters.
        /// </summary>
        internal static string ImageAltMaxLength {
            get {
                return ResourceManager.GetString("ImageAltMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoId must be greater than 0.
        /// </summary>
        internal static string LogoIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("LogoIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MimeType must be a valid format (e.g., &apos;image/png&apos;).
        /// </summary>
        internal static string MimeTypeFormat {
            get {
                return ResourceManager.GetString("MimeTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MimeType is required.
        /// </summary>
        internal static string MimeTypeIsRequired {
            get {
                return ResourceManager.GetString("MimeTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerSourceLinks is required .
        /// </summary>
        internal static string PartnerSourceLinksIsRequired {
            get {
                return ResourceManager.GetString("PartnerSourceLinksIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount must be greater than zero.
        /// </summary>
        internal static string PaymentAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PaymentAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position length must be between {0} and {1} characters.
        /// </summary>
        internal static string PositionMinAndMaxLength {
            get {
                return ResourceManager.GetString("PositionMinAndMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word must not exceed {0} characters.
        /// </summary>
        internal static string RelatedTermWordMaxLength {
            get {
                return ResourceManager.GetString("RelatedTermWordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Streetcode is required.
        /// </summary>
        internal static string StreetCodeIsRequired {
            get {
                return ResourceManager.GetString("StreetCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetUrl must be a valid URL.
        /// </summary>
        internal static string TargetUrlMustBeValid {
            get {
                return ResourceManager.GetString("TargetUrlMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be at most {0} characters.
        /// </summary>
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        internal static string UrlIsRequired {
            get {
                return ResourceManager.GetString("UrlIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlTitle must not exceed {0} characters.
        /// </summary>
        internal static string UrlTitleMaxLength {
            get {
                return ResourceManager.GetString("UrlTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word is required.
        /// </summary>
        internal static string WordIsRequired {
            get {
                return ResourceManager.GetString("WordIsRequired", resourceCulture);
            }
        }
    }
}
